---
title: "Codebook"
author: "Thomas Ziegler"
date: "2015-10-25"
output:
  html_document:
    keep_md: yes
---

##Summary
The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals). 

These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.


##Description of the variables in the tidydata.txt file

###subject
Volunteers coded by Id
        integer
                1..30

###activity
Volunteer activity measured
        string
                1 WALKING
                2 WALKING_UPSTAIRS
                3 WALKING_DOWNSTAIRS
                4 SITTING
                5 STANDING
                6 LAYING
###tBodyAcc-mean-X, tBodyAcc-mean-Y, tBodyAcc-mean-Z
Body acceleration signal mean x,y,z direction
        number
                -1..1
###tBodyAcc-std-X, tBodyAcc-std-Y, tBodyAcc-std-Z
Body acceleration signal standard deviation x,y,z direction
        number
                -1..1
###tBodyAcc-mad-X, tBodyAcc-mad-Y, tBodyAcc-mad-Z
Body acceleration signal Median absolute deviation x,y,z direction
        number
                -1..1
###tBodyAcc-max-X, tBodyAcc-max-Y, tBodyAcc-max-Z
Body acceleration signal Largest value in array x,y,z direction
        number
                -1..1
###tBodyAcc-min-X, tBodyAcc-min-Y, tBodyAcc-min-Z
Body acceleration signal Samallest value in array x,y,z direction
        number
                -1..1
###tBodyAcc-sma
Body acceleration Signal magnitude area
        number
                -1..1
###tBodyAcc-energy-X, tBodyAcc-energy-Y, tBodyAcc-energy-Z
Body acceleration Energy measure x,y,z direction. Sum of the squares divided by the number of values.
        number
                -1..1
###tBodyAcc-iqr-X, tBodyAcc-iqr-Y, tBodyAcc-iqr-Z
Body acceleration, Interquartile range x,y,z direction
        number
                -1..1
###tBodyAcc-entropy-X, tBodyAcc-entropy-Y, tBodyAcc-entropy-Z
Body acceleration, Signal entropy x,y,z direction
        number
                -1..1
###tBodyAcc-arCoeff-X,1, tBodyAcc-arCoeff-X,2, tBodyAcc-arCoeff-X,3, tBodyAcc-arCoeff-X,4
Body acceleration, Autorregresion coefficients with Burg order equal to 4, x direction
        number
                -1..1
###tBodyAcc-arCoeff-Y,1, tBodyAcc-arCoeff-Y,2, tBodyAcc-arCoeff-Y,3, tBodyAcc-arCoeff-Y,4
Body acceleration, Autorregresion coefficients with Burg order equal to 4, y direction
        number
                -1..1
###tBodyAcc-arCoeff-Z,1, tBodyAcc-arCoeff-Z,2, tBodyAcc-arCoeff-Z,3, tBodyAcc-arCoeff-Z,4
Body acceleration, Autorregresion coefficients with Burg order equal to 4, z direction
        number
                -1..1
###tBodyAcc-correlation-X,Y
Body acceleration, correlation coefficient between X,Y
        number
                -1..1
###tBodyAcc-correlation-X,Z
Body acceleration, correlation coefficient between X,Z
        number
                -1..1
###tBodyAcc-correlation-Y,Z
Body acceleration, correlation coefficient between Y,Z
        number
                -1..1
###tGravityAcc-mean-X, tGravityAcc-mean-Y, tGravityAcc-mean-Z
Gravity acceleration signals mean x,y,z direction
        number
                -1..1
###tGravityAcc-std-X, tGravityAcc-std-Y, tGravityAcc-std-Z
Gravity acceleration signal standard deviation x,y,z direction
        number
                -1..1
###tGravityAcc-mad-X, tGravityAcc-mad-Y, tGravityAcc-mad-Z
Gravity acceleration signal Median absolute deviation x,y,z direction
        number
                -1..1
###tGravityAcc-max-X, tGravityAcc-max-Y, tGravityAcc-max-Z
Gravity acceleration signal Largest value in array x,y,z direction
        number
                -1..1
###tGravityAcc-min-X, tGravityAcc-min-Y, tGravityAcc-min-Z
Gravity acceleration signal Samallest value in array z direction
        number
                -1..1
###tGravityAcc-sma
Gravity acceleration Signal magnitude area
        number
                -1..1
###tGravityAcc-energy-X, tGravityAcc-energy-Y, tGravityAcc-energy-Z
Gravity acceleration Energy measure x,y,z direction. Sum of the squares divided by the number of values.
        number
                -1..1
###tGravityAcc-iqr-X, tGravityAcc-iqr-Y, tGravityAcc-iqr-Z
Gravity acceleration, Interquartile range x,y,z direction
        number
                -1..1
###tGravityAcc-entropy-X, tGravityAcc-entropy-Y, tGravityAcc-entropy-Z
Gravity acceleration, Signal entropy x,y,z direction
        number
                -1..1
###tGravityAcc-arCoeff-X,1, tGravityAcc-arCoeff-X,2, tGravityAcc-arCoeff-X,3, tGravityAcc-arCoeff-X,4
Gravity acceleration, Autorregresion coefficients with Burg order equal to 4, x direction
        number
                -1..1
###tGravityAcc-arCoeff-Y,1, tGravityAcc-arCoeff-Y,2, tGravityAcc-arCoeff-Y,3, tGravityAcc-arCoeff-Y,4
Gravity acceleration, Autorregresion coefficients with Burg order equal to 4, y direction
        number
                -1..1
###tGravityAcc-arCoeff-Z,1, tGravityAcc-arCoeff-Z,2, tGravityAcc-arCoeff-Z,3, tGravityAcc-arCoeff-Z,4
Gravity acceleration, Autorregresion coefficients with Burg order equal to 4, z direction
        number
                -1..1
###tGravityAcc-correlation-X,Y
Gravity acceleration, correlation coefficient between X,Y
        number
                -1..1
###tGravityAcc-correlation-X,Z
Gravity acceleration, correlation coefficient between X,Z
        number
                -1..1
###tGravityAcc-correlation-Y,Z
Gravity acceleration, correlation coefficient between Y,Z
        number
                -1..1
###tBodyAccJerk-mean-X, tBodyAccJerk-mean-Y, tBodyAccJerk-mean-Z
Body acceleration Jerk signals mean x,y,z direction
        number
                -1..1
###tBodyAccJerk-std-X, tBodyAccJerk-std-Y tBodyAccJerk-std-Z
Body acceleration Jerk signals standard deviation x,y,z direction
        number
                -1..1
###tBodyAccJerk-mad-X, tBodyAccJerk-mad-Y, tBodyAccJerk-mad-Z
Body acceleration Jerksignal Median absolute deviation x,y,z direction
        number
                -1..1
###tBodyAccJerk-max-X, tBodyAccJerk-max-Y, tBodyAccJerk-max-Z
Body acceleration Jerksignal Largest value in array x,y,z direction
        number
                -1..1
###tBodyAccJerk-min-X, tBodyAccJerk-min-Y, tBodyAccJerk-min-Z
Body acceleration Jerksignal Lowest value in array x,y,z direction
        number
                -1..1
###tBodyAccJerk-sma
Body acceleration Jerk Signal magnitude area
        number
                -1..1
###tBodyAccJerk-energy-X, tBodyAccJerk-energy-Y, tBodyAccJerk-energy-Z
Body acceleration Jerk Energy measure x,y,z direction. Sum of the squares divided by the number of values.
        number
                -1..1
###tBodyAccJerk-iqr-X, tBodyAccJerk-iqr-Y, tBodyAccJerk-iqr-Z
Body acceleration, Jerk Interquartile range x,y,z direction
        number
                -1..1
###tBodyAccJerk-entropy-X, tBodyAccJerk-entropy-Y, tBodyAccJerk-entropy-Z
Body acceleration, Jerk Signal entropy x,y,z direction
        number
                -1..1
###tBodyAccJerk-arCoeff-X,1, tBodyAccJerk-arCoeff-X,2, tBodyAccJerk-arCoeff-X,3, tBodyAccJerk-arCoeff-X,4
Body acceleration, Jerk Autorregresion coefficients with Burg order equal to 4, x direction
        number
                -1..1
###tBodyAccJerk-arCoeff-Y,1,tBodyAccJerk-arCoeff-Y,2, tBodyAccJerk-arCoeff-Y,3, tBodyAccJerk-arCoeff-Y,4
Body acceleration, Jerk Autorregresion coefficients with Burg order equal to 4, y direction
        number
                -1..1
###tBodyAccJerk-arCoeff-Z,1, tBodyAccJerk-arCoeff-Z,2, tBodyAccJerk-arCoeff-Z,3, tBodyAccJerk-arCoeff-Z,4
Body acceleration, Jerk Autorregresion coefficients with Burg order equal to 4, z direction
        number
                -1..1
###tBodyAccJerk-correlation-X,Y
Body acceleration, Jerk correlation coefficient between X,Y
        number
                -1..1
###tBodyAccJerk-correlation-X,Z
Body acceleration, Jerk correlation coefficient between X,Z
        number
                -1..1
###tBodyAccJerk-correlation-Y,Z
Body acceleration, Jerk correlation coefficient between Y,Z
        number
                -1..1
###tBodyGyro-mean-X, tBodyGyro-mean-Y, tBodyGyro-mean-Z
Body gyroscope signal mean x,y,z direction
        number
                -1..1
###tBodyGyro-std-X, tBodyGyro-std-Y, tBodyGyro-std-Z
Body gyroscope signal standard deviation x,y,z direction
        number
                -1..1
###tBodyGyro-mad-X, tBodyGyro-mad-Y, tBodyGyro-mad-Z
Body gyroscope signal Median absolute deviation x,y,z direction
        number
                -1..1
###tBodyGyro-max-X, tBodyGyro-max-Y, tBodyGyro-max-Z
Body gyroscope signal Largest value in array x,y,z direction
        number
                -1..1
###tBodyGyro-min-X, tBodyGyro-min-Y, tBodyGyro-min-Z
Body gyroscope signal Samallest value in array x,y,z direction
        number
                -1..1
###tBodyGyro-sma
Body gyroscope Signal magnitude area
        number
                -1..1
###tBodyGyro-energy-X, tBodyGyro-energy-Y, tBodyGyro-energy-Z
Body gyroscope Energy measure x,y,z direction. Sum of the squares divided by the number of values.
        number
                -1..1
###tBodyGyro-iqr-X, tBodyGyro-iqr-Y, tBodyGyro-iqr-Z
Body gyroscope, Interquartile range x,y,z direction
        number
                -1..1
###tBodyGyro-entropy-X, tBodyGyro-entropy-Y, tBodyGyro-entropy-Z
Body gyroscope, Signal entropy x,y,z direction
        number
                -1..1
###tBodyGyro-arCoeff-X,1, tBodyGyro-arCoeff-X,2, tBodyGyro-arCoeff-X,3, tBodyGyro-arCoeff-X,4
Body gyroscope, Autorregresion coefficients with Burg order equal to 4, x direction
        number
                -1..1
###tBodyGyro-arCoeff-Y,1, tBodyGyro-arCoeff-Y,2, tBodyGyro-arCoeff-Y,3, tBodyGyro-arCoeff-Y,4
Body gyroscope, Autorregresion coefficients with Burg order equal to 4, y direction
        number
                -1..1
###tBodyGyro-arCoeff-Z,, tBodyGyro-arCoeff-Z,2, tBodyGyro-arCoeff-Z,3, tBodyGyro-arCoeff-Z,4
Body gyroscope, Autorregresion coefficients with Burg order equal to 4, z direction
        number
                -1..1
###tBodyGyro-correlation-X,Y
Body gyroscope, correlation coefficient between X,Y
        number
                -1..1
###tBodyGyro-correlation-X,Z
Body gyroscope, correlation coefficient between X,Z
        number
                -1..1
###tBodyGyro-correlation-Y,Z
Body gyroscope, correlation coefficient between Y,Z
        number
                -1..1
###tBodyGyroJerk-mean-X, tBodyGyroJerk-mean-Y, tBodyGyroJerk-mean-Z
Body gyroscope Jerk signal mean x,y,z direction
        number
                -1..1
###tBodyGyroJerk-std-X, tBodyGyroJerk-std-Y, tBodyGyroJerk-std-Z
Body gyroscope Jerk signal standard deviation x,y,z direction
        number
                -1..1
###tBodyGyroJerk-mad-X, tBodyGyroJerk-mad-Y, tBodyGyroJerk-mad-Z
Body gyroscope Jerk signal Median absolute deviation x,y,z direction
        number
                -1..1
###tBodyGyroJerk-max-X, tBodyGyroJerk-max-Y, tBodyGyroJerk-max-Z
Body gyroscope Jerk signal Largest value in array x,y,z direction
        number
                -1..1
###tBodyGyroJerk-min-X, tBodyGyroJerk-min-Y, tBodyGyroJerk-min-Z
Body gyroscope Jerk signal Smallest value in array x,y,z direction
        number
                -1..1
###tBodyGyroJerk-sma
Body gyroscope Jerk Signal magnitude area
        number
                -1..1
###tBodyGyroJerk-energy-X, tBodyGyroJerk-energy-Y, tBodyGyroJerk-energy-Z
Body gyroscope Jerk Energy measure x,y,z direction. Sum of the squares divided by the number of values.
        number
                -1..1
###tBodyGyroJerk-iqr-X, tBodyGyroJerk-iqr-Y, tBodyGyroJerk-iqr-Z
Body gyroscope Jerk, Interquartile range x,y,z direction
        number
                -1..1
###tBodyGyroJerk-entropy-X, tBodyGyroJerk-entropy-Y, tBodyGyroJerk-entropy-Z
Body gyroscope Jerk, Signal entropy x,y,z direction
        number
                -1..1
###tBodyGyroJerk-arCoeff-X,1, tBodyGyroJerk-arCoeff-X,2, tBodyGyroJerk-arCoeff-X,3, tBodyGyroJerk-arCoeff-X,4
Body gyroscope Jerk, Autorregresion coefficients with Burg order equal to 4, x direction
        number
                -1..1
###tBodyGyroJerk-arCoeff-Y,1, tBodyGyroJerk-arCoeff-Y,2, tBodyGyroJerk-arCoeff-Y,3, tBodyGyroJerk-arCoeff-Y,4
Body gyroscope Jerk, Autorregresion coefficients with Burg order equal to 4, y direction
        number
                -1..1
###tBodyGyroJerk-arCoeff-Z,1, tBodyGyroJerk-arCoeff-Z,2, tBodyGyroJerk-arCoeff-Z,3, tBodyGyroJerk-arCoeff-Z,4
Body gyroscope Jerk, Autorregresion coefficients with Burg order equal to 4, z direction
        number
                -1..1
###tBodyGyroJerk-correlation-X,Y
Body gyroscope Jerk, correlation coefficient between X,Y
        number
                -1..1
###tBodyGyroJerk-correlation-X,Z
Body gyroscope Jerk, correlation coefficient between X,Z
        number
                -1..1
###tBodyGyroJerk-correlation-Y,Z
Body gyroscope Jerk, correlation coefficient between Y,Z
        number
                -1..1

###tBodyAccMag-mean
Body acceleration magnitude of three-dimensional signal mean x,y,z direction
        number
                -1..1
###tBodyAccMag-std
Body acceleration magnitude signal standard deviation x,y,z direction
        number
                -1..1
###tBodyAccMag-mad
Body acceleration magnitude signal Median absolute deviation x,y,z direction
        number
                -1..1
###tBodyAccMag-max
Body acceleration magnitude signal Largest value in array x,y,z direction
        number
                -1..1
###tBodyAccMag-min
Body acceleration magnitude signal Samallest value in array x,y,z direction
        number
                -1..1
###tBodyAccMag-sma
Body acceleration magnitude Signal magnitude area
        number
                -1..1
###tBodyAccMag-energy
Body acceleration magnitude Energy measure x,y,z direction. Sum of the squares divided by the number of values.
        number
                -1..1
###tBodyAccMag-iqr
Body acceleration magnitude, Interquartile range x,y,z direction
        number
                -1..1
###tBodyAccMag-entropy
Body acceleration magnitude, Signal entropy x,y,z direction
        number
                -1..1
###tBodyAccMag-arCoeff1, tBodyAccMag-arCoeff2, tBodyAccMag-arCoeff3, tBodyAccMag-arCoeff4
Body acceleration magnitude, Autorregresion coefficients with Burg order equal to 4, x direction
        number
                -1..1
###tGravityAccMag-mean
Gravity acceleration magnitude of three-dimensional signal mean x,y,z direction
        number
                -1..1
###tGravityAccMag-std
Gravity acceleration magnitude of three-dimensional signal standard deviation x,y,z direction
        number
                -1..1
###tGravityAccMag-mad
Gravity acceleration magnitude of three-dimensional signal Median absolute deviation x,y,z direction
        number
                -1..1
###tGravityAccMag-max
Gravity acceleration magnitude of three-dimensional signal Largest value in array x,y,z direction
        number
                -1..1
###tGravityAccMag-min
Gravity acceleration magnitude of three-dimensional signal Samallest value in array x,y,z direction
        number
                -1..1
###tGravityAccMag-sma
Gravity acceleration magnitude of three-dimensional Signal magnitude area
        number
                -1..1
###tGravityAccMag-energy
Gravity acceleration magnitude of three-dimensional Energy measure x,y,z direction. Sum of the squares 
        number divided by the number of values.
                -1..1
###tGravityAccMag-iqr
Gravity acceleration magnitude, Interquartile range x,y,z direction
        number
                -1..1
###tGravityAccMag-entropy
Gravity acceleration magnitude of three-dimensional Signal entropy x,y,z direction
        number
                -1..1
###tGravityAccMag-arCoeff1, tGravityAccMag-arCoeff2, tGravityAccMag-arCoeff3, tGravityAccMag-arCoeff4
Gravity acceleration magnitude of three-dimensional signal, Autorregresion coefficients with Burg order 
equal to 4
        number
                -1..1
###tBodyAccJerkMag-mean
Body acceleration magnitude of three-dimensional Jerk signal mean x,y,z direction
        number
                -1..1
###tBodyAccJerkMag-std
Body acceleration magnitude of three-dimensional Jerk signal standard deviation x,y,z direction
        number
                -1..1
###tBodyAccJerkMag-mad
Body acceleration magnitude of three-dimensional Jerk signal Median absolute deviation x,y,z direction
        number
                -1..1
###tBodyAccJerkMag-max
Body acceleration magnitude of three-dimensional Jerk signal Largest value in array x,y,z direction
        number
                -1..1
###tBodyAccJerkMag-min
Body acceleration magnitude of three-dimensional Jerk signal Samallest value in array x,y,z direction
        number
                -1..1
###tBodyAccJerkMag-sma
Body acceleration magnitude of three-dimensional Jerk Signal magnitude area
        number
                -1..1
###tBodyAccJerkMag-energy
Body acceleration magnitude of three-dimensional Jerk signal Energy measure x,y,z direction. Sum of the squares divided by the number of values.
        number
                -1..1
###tBodyAccJerkMag-iqr
Body acceleration magnitude of three-dimensional Jerk signal, Interquartile range x,y,z direction
        number
                -1..1
###tBodyAccJerkMag-entropy
Body acceleration magnitude of three-dimensional Jerk Signal entropy x,y,z direction
        number
                -1..1
###tBodyAccJerkMag-arCoeff1, tBodyAccJerkMag-arCoeff2, tBodyAccJerkMag-arCoeff3, tBodyAccJerkMag-arCoeff4
Body acceleration magnitude of three-dimensional Jerk signal, Autorregresion coefficients with Burg order equal to 4
        number
                -1..1
###tBodyGyroMag-mean
Body gyroscope magnitude of three-dimensional signal mean x,y,z direction
        number
                -1..1
###tBodyGyroMag-std
Body gyroscope magnitude of three-dimensional signal standard deviation x,y,z direction
        number
                -1..1
###tBodyGyroMag-mad
Body gyroscope magnitude of three-dimensional signal Median absolute deviation x,y,z direction
        number
                -1..1
###tBodyGyroMag-max
Body gyroscope magnitude of three-dimensional signal Largest value in array x,y,z direction
        number
                -1..1
###tBodyGyroMag-min
Body gyroscope magnitude of three-dimensional signal Samallest value in array x,y,z direction
        number
                -1..1
###tBodyGyroMag-sma
Body gyroscope magnitude of three-dimensional Signal magnitude area
        number
                -1..1
###tBodyGyroMag-energy
Body gyroscope magnitude of three-dimensional signal Energy measure x,y,z direction. Sum of the squares 
        number divided by the number of values.
                -1..1
###tBodyGyroMag-iqr
Body gyroscope magnitude of three-dimensional signal, Interquartile range x,y,z direction
        number
                -1..1
###tBodyGyroMag-entropy
Body gyroscope magnitude of three-dimensional Signal entropy x,y,z direction
        number
                -1..1
###tBodyGyroMag-arCoeff1, tBodyGyroMag-arCoeff2, tBodyGyroMag-arCoeff3, tBodyGyroMag-arCoeff4
Body gyroscope magnitude of three-dimensional signal, Autorregresion coefficients with Burg order equal to 4
        number
                -1..1
###tBodyGyroJerkMag-mean
Body gyroscope magnitude of three-dimensional Jerk signal mean x,y,z direction
        number
                -1..1
###tBodyGyroJerkMag-std
Body gyroscope magnitude of three-dimensional Jerk signal standard deviation x,y,z direction
        number
                -1..1
###tBodyGyroJerkMag-mad
Body gyroscope magnitude of three-dimensional Jerk signal Median absolute deviation x,y,z direction
        number
                -1..1
###tBodyGyroJerkMag-max
Body gyroscope magnitude of three-dimensional Jerk signal Largest value in array x,y,z direction
        number
                -1..1
###tBodyGyroJerkMag-min
Body gyroscope magnitude of three-dimensional Jerk signal Samallest value in array x,y,z direction
        number
                -1..1
###tBodyGyroJerkMag-sma
Body gyroscope magnitude of three-dimensional Jerk Signal magnitude area
        number
                -1..1
###tBodyGyroJerkMag-energy
Body gyroscope magnitude of three-dimensional Jerk signal Energy measure x,y,z direction. Sum of the squares 
        number divided by the number of values.
                -1..1
###tBodyGyroJerkMag-iqr
Body gyroscope magnitude of three-dimensional Jerk signal, Interquartile range x,y,z direction
        number
                -1..1
###tBodyGyroJerkMag-entropy
Body gyroscope magnitude of three-dimensional Jerk Signal entropy x,y,z direction
        number
                -1..1
###tBodyGyroJerkMag-arCoeff1, tBodyGyroJerkMag-arCoeff2, tBodyGyroJerkMag-arCoeff3, tBodyGyroJerkMag-arCoeff4
Body gyroscope magnitude of three-dimensional Jerk signal, Autorregresion coefficients with Burg order equal 
        number
                -1..1to 4
###fBodyAcc-mean-X, fBodyAcc-mean-Y, fBodyAcc-mean-Z
Body acceleration frequency domain signal mean x,y,z direction
        number
                -1..1
###fBodyAcc-std-X, fBodyAcc-std-Y, fBodyAcc-std-Z
Body acceleration frequency domain signal standard deviation x,y,z direction
        number
                -1..1
###fBodyAcc-mad-X, fBodyAcc-mad-Y, fBodyAcc-mad-Z
Body acceleration frequency signal Median absolute deviation x,y,z direction
        number
                -1..1
###fBodyAcc-max-X, fBodyAcc-max-Y, fBodyAcc-max-Z
Body acceleration frequency signal Largest value in array x,y,z direction
        number
                -1..1
###fBodyAcc-min-X, fBodyAcc-min-Y, fBodyAcc-min-Z
Body acceleration frequency signal Smallest value in array x,y,z direction
        number
                -1..1
###fBodyAcc-sma
Body acceleration frequency Signal magnitude area
        number
                -1..1
###fBodyAcc-energy-X, fBodyAcc-energy-Y, fBodyAcc-energy-Z
Body acceleration frequency signal Energy measure x,y,z direction. Sum of the squares divided by the number of values.
        number
                -1..1
###fBodyAcc-iqr-X, fBodyAcc-iqr-Y, fBodyAcc-iqr-Z
Body acceleration frequency signal, Interquartile range x,y,z direction
        number
                -1..1
###fBodyAcc-entropy-X, fBodyAcc-entropy-Y, fBodyAcc-entropy-Z
Body acceleration, frequencySignal entropy x,y,z direction
        number
                -1..1
###fBodyAcc-maxInds-X, fBodyAcc-maxInds-Y, fBodyAcc-maxInds-Z
Body acceleration index of the frequency component with largest magnitude x,y,z direction 
        number
                -1..1
###fBodyAcc-meanFreq-X, fBodyAcc-meanFreq-Y, fBodyAcc-meanFreq-Z
Body acceleration Weighted average of the frequency components to obtain a mean frequency x,y,z direction
        number
                -1..1
###fBodyAcc-skewness-X, fBodyAcc-skewness-Y, fBodyAcc-skewness-Z
Body acceleration, skewness of the frequency domain signal x,y,z direction
        number
                -1..1
###fBodyAcc-kurtosis-X, fBodyAcc-kurtosis-Y, fBodyAcc-kurtosis-Z
Body acceleration, kurtosis of the frequency domain signal x,y,z direction
        number
                -1..1
###fBodyAcc-bandsEnergy-1,8, fBodyAcc-bandsEnergy-9,16, fBodyAcc-bandsEnergy-17,24, fBodyAcc-bandsEnergy-25,32, fBodyAcc-bandsEnergy-33,40, fBodyAcc-bandsEnergy-41,48, fBodyAcc-bandsEnergy-49,56, fBodyAcc-bandsEnergy-57,64, fBodyAcc-bandsEnergy-1,16, fBodyAcc-bandsEnergy-17,32, fBodyAcc-bandsEnergy-33,48, fBodyAcc-bandsEnergy-49,64, fBodyAcc-bandsEnergy-1,24, fBodyAcc-bandsEnergy-25,48, fBodyAcc-bandsEnergy-1,8, fBodyAcc-bandsEnergy-9,16, fBodyAcc-bandsEnergy-17,24, fBodyAcc-bandsEnergy-25,32, fBodyAcc-bandsEnergy-33,40, fBodyAcc-bandsEnergy-41,48, fBodyAcc-bandsEnergy-49,56, fBodyAcc-bandsEnergy-57,64, fBodyAcc-bandsEnergy-1,16, fBodyAcc-bandsEnergy-17,32, fBodyAcc-bandsEnergy-33,48, fBodyAcc-bandsEnergy-49,64, fBodyAcc-bandsEnergy-1,24, fBodyAcc-bandsEnergy-25,48, fBodyAcc-bandsEnergy-1,8, fBodyAcc-bandsEnergy-9,16, fBodyAcc-bandsEnergy-17,24, fBodyAcc-bandsEnergy-25,32, fBodyAcc-bandsEnergy-33,40, fBodyAcc-bandsEnergy-41,48, fBodyAcc-bandsEnergy-49,56, fBodyAcc-bandsEnergy-57,64, fBodyAcc-bandsEnergy-1,16, fBodyAcc-bandsEnergy-17,32, fBodyAcc-bandsEnergy-33,48, fBodyAcc-bandsEnergy-49,64, fBodyAcc-bandsEnergy-1,24, fBodyAcc-bandsEnergy-25,48
Body acceleration, Energy of a frequency interval within the 64 bins of the FFT of each window.
        number
                -1..1
###fBodyAccJerk-mean-X, fBodyAccJerk-mean-Y, fBodyAccJerk-mean-Z
Body acceleration frequency domain Jerk signal mean x,y,z direction
        number
                -1..1
###fBodyAccJerk-std-X, fBodyAccJerk-std-Y, fBodyAccJerk-std-Z
Body acceleration frequency domain Jerk signal standard deviation x,y,z direction
        number
                -1..1
###fBodyAccJerk-mad-X, fBodyAccJerk-mad-Y, fBodyAccJerk-mad-Z
Body acceleration frequency domain Jerk signal Median absolute deviation x,y,z direction
        number
                -1..1
###fBodyAccJerk-max-X, fBodyAccJerk-max-Y, fBodyAccJerk-max-Z
Body acceleration frequency domain Jerk signal Largest value in array x,y,z direction
        number
                -1..1
###fBodyAccJerk-min-X, fBodyAccJerk-min-Y, fBodyAccJerk-min-Z
Body acceleration frequency domain Jerk signal Samallest value in array x,y,z direction
        number
                -1..1
###fBodyAccJerk-sma
Body acceleration frequency domain Jerk Signal magnitude area
        number
                -1..1
###fBodyAccJerk-energy-X, fBodyAccJerk-energy-Y, fBodyAccJerk-energy-Z
Body acceleration frequency domain Jerk signal Energy measure x,y,z direction. Sum of the squares divided by 
        number
                -1..1the number of values.
###fBodyAccJerk-iqr-X, fBodyAccJerk-iqr-Y, fBodyAccJerk-iqr-Z
Body acceleration frequency domain Jerk signal, Interquartile range x,y,z direction
        number
                -1..1
###fBodyAccJerk-entropy-X, fBodyAccJerk-entropy-Y, fBodyAccJerk-entropy-Z
Body acceleration frequency domain Jerk Signal entropy x,y,z direction
        number
                -1..1
###fBodyAccJerk-maxInds-X, fBodyAccJerk-maxInds-Y, fBodyAccJerk-maxInds-Z
Body acceleration frequency domain Jerk index of the frequency component with largest magnitude x,y,z direction 
        number
                -1..1
###fBodyAccJerk-meanFreq-X, fBodyAccJerk-meanFreq-Y, fBodyAccJerk-meanFreq-Z
Body acceleration frequency domain Jerk, Weighted average of the frequency components to obtain a mean frequency x,y,z direction
        number
                -1..1
###fBodyAccJerk-skewness-X, fBodyAccJerk-skewness-Y, fBodyAccJerk-skewness-Z
Body acceleration, skewness of the frequency domain Jerk signal x,y,z direction
        number
                -1..1
###fBodyAccJerk-kurtosis-X, fBodyAccJerk-kurtosis-Y, fBodyAccJerk-kurtosis-Z
Body acceleration, kurtosis of the frequency domain Jerk signal x,y,z direction
        number
                -1..1
###fBodyAccJerk-bandsEnergy-1,8, fBodyAccJerk-bandsEnergy-9,16, fBodyAccJerk-bandsEnergy-17,24, fBodyAccJerk-bandsEnergy-25,32, fBodyAccJerk-bandsEnergy-33,40, fBodyAccJerk-bandsEnergy-41,48, fBodyAccJerk-bandsEnergy-49,56, fBodyAccJerk-bandsEnergy-57,64, fBodyAccJerk-bandsEnergy-1,16, fBodyAccJerk-bandsEnergy-17,32, fBodyAccJerk-bandsEnergy-33,48, fBodyAccJerk-bandsEnergy-49,64, fBodyAccJerk-bandsEnergy-1,24, fBodyAccJerk-bandsEnergy-25,48, fBodyAccJerk-bandsEnergy-1,8, fBodyAccJerk-bandsEnergy-9,16, fBodyAccJerk-bandsEnergy-17,24, fBodyAccJerk-bandsEnergy-25,32, fBodyAccJerk-bandsEnergy-33,40, fBodyAccJerk-bandsEnergy-41,48, fBodyAccJerk-bandsEnergy-49,56, fBodyAccJerk-bandsEnergy-57,64, fBodyAccJerk-bandsEnergy-1,16, fBodyAccJerk-bandsEnergy-17,32, fBodyAccJerk-bandsEnergy-33,48, fBodyAccJerk-bandsEnergy-49,64, fBodyAccJerk-bandsEnergy-1,24, fBodyAccJerk-bandsEnergy-25,48, fBodyAccJerk-bandsEnergy-1,8, fBodyAccJerk-bandsEnergy-9,16, fBodyAccJerk-bandsEnergy-17,24, fBodyAccJerk-bandsEnergy-25,32, fBodyAccJerk-bandsEnergy-33,40, fBodyAccJerk-bandsEnergy-41,48, fBodyAccJerk-bandsEnergy-49,56, fBodyAccJerk-bandsEnergy-57,64, fBodyAccJerk-bandsEnergy-1,16, fBodyAccJerk-bandsEnergy-17,32, fBodyAccJerk-bandsEnergy-33,48, fBodyAccJerk-bandsEnergy-49,64, fBodyAccJerk-bandsEnergy-1,24, fBodyAccJerk-bandsEnergy-25,48
Body acceleration frequency domain Jerk, Energy of a frequency interval within the 64 bins of the FFT of each window.
        number
                -1..1
###fBodyGyro-mean-X, fBodyGyro-mean-Y,fBodyGyro-mean-Z
Body gyroscope frequency domain signal mean x,y,z direction
        number
                -1..1
###fBodyGyro-std-X, fBodyGyro-std-Y, fBodyGyro-std-Z
Body gyroscope frequency domain signal standard deviation x,y,z direction
        number
                -1..1
###fBodyGyro-mad-X, fBodyGyro-mad-Y, fBodyGyro-mad-Z
Body gyroscope frequency domain signal Median absolute deviation x,y,z direction
        number
                -1..1
###fBodyGyro-max-X, fBodyGyro-max-Y, fBodyGyro-max-Z
Body gyroscope frequency domain signal Largest value in array x,y,z direction
        number
                -1..1
###fBodyGyro-min-X, fBodyGyro-min-Y, fBodyGyro-min-Z
Body gyroscope frequency domain signal Smallest value in array x,y,z direction
        number
                -1..1
###fBodyGyro-sma
Body gyroscope frequency domain Signal magnitude area
        number
                -1..1
###fBodyGyro-energy-X, fBodyGyro-energy-Y, fBodyGyro-energy-Z
Body gyroscope frequency domain Energy measure x,y,z direction. Sum of the squares divided by the number of values.
        number
                -1..1
###fBodyGyro-iqr-X, fBodyGyro-iqr-Y, fBodyGyro-iqr-Z
Body gyroscope frequency domain, Interquartile range x,y,z direction
        number
                -1..1
###fBodyGyro-entropy-X, fBodyGyro-entropy-Y, fBodyGyro-entropy-Z
Body gyroscope frequency domain, Signal entropy x,y,z direction
        number
                -1..1
###fBodyGyro-maxInds-X, fBodyGyro-maxInds-Y, fBodyGyro-maxInds-Z
Body gyroscope frequency domain index of the frequency component with largest magnitude x,y,z direction 
        number
                -1..1
###fBodyGyro-meanFreq-X, fBodyGyro-meanFreq-Y, fBodyGyro-meanFreq-Z
Body gyroscope frequency domain, Weighted average of the frequency components to obtain a mean frequency x,y,z direction
        number
                -1..1
###fBodyGyro-skewness-X, fBodyGyro-skewness-Y, fBodyGyro-skewness-Z
Body gyroscope frequency domain, skewness of the frequency domain Jerk signal x,y,z direction
        number
                -1..1
###fBodyGyro-kurtosis-X, fBodyGyro-kurtosis-Y, fBodyGyro-kurtosis-Z
Body gyroscope frequency domain, kurtosis of the frequency domain Jerk signal x,y,z direction
        number
                -1..1
###fBodyGyro-bandsEnergy-1,8, fBodyGyro-bandsEnergy-9,16, fBodyGyro-bandsEnergy-17,24, fBodyGyro-bandsEnergy-25,32, fBodyGyro-bandsEnergy-33,40, fBodyGyro-bandsEnergy-41,48, fBodyGyro-bandsEnergy-49,56, fBodyGyro-bandsEnergy-57,64, fBodyGyro-bandsEnergy-1,16, fBodyGyro-bandsEnergy-17,32, fBodyGyro-bandsEnergy-33,48, fBodyGyro-bandsEnergy-49,64, fBodyGyro-bandsEnergy-1,24, fBodyGyro-bandsEnergy-25,48, fBodyGyro-bandsEnergy-1,8, fBodyGyro-bandsEnergy-9,16, fBodyGyro-bandsEnergy-17,24, fBodyGyro-bandsEnergy-25,32, fBodyGyro-bandsEnergy-33,40, fBodyGyro-bandsEnergy-41,48, fBodyGyro-bandsEnergy-49,56, fBodyGyro-bandsEnergy-57,64, fBodyGyro-bandsEnergy-1,16, fBodyGyro-bandsEnergy-17,32, fBodyGyro-bandsEnergy-33,48, fBodyGyro-bandsEnergy-49,64, fBodyGyro-bandsEnergy-1,24, fBodyGyro-bandsEnergy-25,48, fBodyGyro-bandsEnergy-1,8, fBodyGyro-bandsEnergy-9,16, fBodyGyro-bandsEnergy-17,24, fBodyGyro-bandsEnergy-25,32, fBodyGyro-bandsEnergy-33,40, fBodyGyro-bandsEnergy-41,48, fBodyGyro-bandsEnergy-49,56, fBodyGyro-bandsEnergy-57,64, fBodyGyro-bandsEnergy-1,16, fBodyGyro-bandsEnergy-17,32, fBodyGyro-bandsEnergy-33,48, fBodyGyro-bandsEnergy-49,64, fBodyGyro-bandsEnergy-1,24, fBodyGyro-bandsEnergy-25,48
Body gyroscope frequency domain, Energy of a frequency interval within the 64 bins of the FFT of each window.
        number
                -1..1
###fBodyAccMag-mean
Body acceleration magnitude of three-dimensional frequency domain signal mean
        number
                -1..1
###fBodyAccMag-std
Body acceleration magnitude of three-dimensional frequency signal standard deviation
        number
                -1..1
###fBodyAccMag-mad
Body acceleration magnitude of three-dimensional frequency signal Median absolute deviation
        number
                -1..1
###fBodyAccMag-max
Body acceleration magnitude of three-dimensional frequency signal Largest value in array
        number
                -1..1
###fBodyAccMag-min
Body acceleration magnitude of three-dimensional frequency signal Samallest value in array
        number
                -1..1
###fBodyAccMag-sma
Body acceleration magnitude of three-dimensional frequency Signal magnitude area
        number
                -1..1
###fBodyAccMag-energy
Body acceleration magnitude of three-dimensional frequency Energy measure. Sum of the 
squares divided by the number of values.
        number
                -1..1
###fBodyAccMag-iqr
Body acceleration magnitude of three-dimensional frequency signal, Interquartile range
        number
                -1..1
###fBodyAccMag-entropy
Body acceleration magnitude of three-dimensional frequency Signal entropy
        number
                -1..1
###fBodyAccMag-maxInds
Body acceleration magnitude of three-dimensional frequency Signal, index of the frequency component with largest magnitude
        number
                -1..1
###fBodyAccMag-meanFreq
Body acceleration magnitude of three-dimensional frequency Signal, Weighted average of the frequency components to obtain a mean frequency
        number
                -1..1
###fBodyAccMag-skewness
Body acceleration magnitude of three-dimensional frequency Signal, skewness of the frequency domain Jerk signal
        number
                -1..1
###fBodyAccMag-kurtosis
Body acceleration magnitude of three-dimensional frequency signal, kurtosis of the frequency domain Jerk signal
        number
                -1..1
###fBodyBodyAccJerkMag-mean
Body acceleration magnitude of three-dimensional frequency domain Jerk signal mean
        number
                -1..1
###fBodyBodyAccJerkMag-std
Body acceleration magnitude of three-dimensional frequency Jerk signal standard deviation
        number
                -1..1
###fBodyBodyAccJerkMag-mad
Body acceleration magnitude of three-dimensional frequency Jerk signal Median absolute deviation
        number
                -1..1
###fBodyBodyAccJerkMag-max
Body acceleration magnitude of three-dimensional frequency Jerk signal Largest value in array
        number
                -1..1
###fBodyBodyAccJerkMag-min
Body acceleration magnitude of three-dimensional frequency Jerk signal Smallest value in array
        number
                -1..1
###fBodyBodyAccJerkMag-sma
Body acceleration magnitude of three-dimensional frequency Jerk Signal magnitude area
        number
                -1..1
###fBodyBodyAccJerkMag-energy
Body acceleration magnitude of three-dimensional Jerk frequency Energy measure. Sum of the 
squares divided by the number of values.
        number
                -1..1
###fBodyBodyAccJerkMag-iqr
Body acceleration magnitude of three-dimensional frequency Jerk signal, Interquartile range
        number
                -1..1
###fBodyBodyAccJerkMag-entropy
Body acceleration magnitude of three-dimensional frequency Jerk Signal entropy
        number
                -1..1
###fBodyBodyAccJerkMag-maxInds
Body acceleration magnitude of three-dimensional frequency Jerk Signal, index of the frequency component with largest magnitude
        number
                -1..1
###fBodyBodyAccJerkMag-meanFreq
Body acceleration magnitude of three-dimensional frequency Jerk Signal, Weighted average of the frequency components to obtain a mean frequency
        number
                -1..1
###fBodyBodyAccJerkMag-skewness
Body acceleration magnitude of three-dimensional frequency Jerk Signal, skewness of the frequency domain Jerk signal
        number
                -1..1
###fBodyBodyAccJerkMag-kurtosis
Body acceleration magnitude of three-dimensional frequency Jerk signal, kurtosis of the frequency domain Jerk signal
        number
                -1..1
###fBodyBodyGyroMag-mean
Body gyroscope magnitude of three-dimensional frequency domain signal mean
        number
                -1..1
###fBodyBodyGyroMag-std
Body gyroscope magnitude of three-dimensional frequency domain signal standard deviation
        number
                -1..1
###fBodyBodyGyroMag-mad
Body gyroscope magnitude of three-dimensional frequency domain signal Median absolute deviation
        number
                -1..1
###fBodyBodyGyroMag-max
Body gyroscope magnitude of three-dimensional frequency domain signal Largest value in array
        number
                -1..1
###fBodyBodyGyroMag-min
Body gyroscope magnitude of three-dimensional frequency domain signal Smallest value in array
        number
                -1..1
###fBodyBodyGyroMag-sma
Body gyroscope magnitude of three-dimensional frequency domain signal Samallest value in array
        number
                -1..1
###fBodyBodyGyroMag-energy
Body gyroscope magnitude of three-dimensional frequency domain signal Energy measure. Sum of the squares divided by the number of values.
        number
                -1..1
###fBodyBodyGyroMag-iqr
Body gyroscope magnitude of three-dimensional frequency domain signal, Interquartile range
        number
                -1..1
###fBodyBodyGyroMag-entropy
Body gyroscope magnitude of three-dimensional frequency domain Signal entropy
        number
                -1..1
###fBodyBodyGyroMag-maxInds
Body gyroscope magnitude of three-dimensional frequency domain Signal, index of the frequency component with largest magnitude x,y,z direction 
        number
                -1..1
###fBodyBodyGyroMag-meanFreq
Body gyroscope magnitude of three-dimensional frequency domain Signal, Weighted average of the frequency components to obtain a mean frequency x,y,z direction
        number
                -1..1
###fBodyBodyGyroMag-skewness
Body gyroscope magnitude of three-dimensional frequency domain Signal,
        number
                -1..1
###fBodyBodyGyroMag-kurtosis
Body gyroscope magnitude of three-dimensional frequency domain Signal,
        number
                -1..1
###fBodyBodyGyroJerkMag-mean
Body gyroscope magnitude of three-dimensional frequency domain Jerk Signal,
        number
                -1..1
###fBodyBodyGyroJerkMag-std
Body gyroscope magnitude of three-dimensional frequency domain Jerk Signal, standard deviation
        number
                -1..1
###fBodyBodyGyroJerkMag-mad
Body gyroscope magnitude of three-dimensional frequency domain Jerk Signal, Median absolute deviation
        number
                -1..1
###fBodyBodyGyroJerkMag-max
Body gyroscope magnitude of three-dimensional frequency domain Jerk Signal, Largest value in array
        number
                -1..1
###fBodyBodyGyroJerkMag-min
Body gyroscope magnitude of three-dimensional frequency domain Jerk Signal, Samallest value in array
        number
                -1..1
###fBodyBodyGyroJerkMag-sma
Body gyroscope magnitude of three-dimensional frequency domain Jerk Signal, magnitude area
        number
                -1..1
###fBodyBodyGyroJerkMag-energy
Body gyroscope magnitude of three-dimensional frequency domain Jerk Signal Energy measure. Sum of the squares divided by the number of values.
        number
                -1..1
###fBodyBodyGyroJerkMag-iqr
Body gyroscope magnitude of three-dimensional frequency domain Jerk Signal, Interquartile range
        number
                -1..1
###fBodyBodyGyroJerkMag-entropy
Body gyroscope magnitude of three-dimensional frequency domain Jerk Signal, Signal entropy
        number
                -1..1
###fBodyBodyGyroJerkMag-maxInds
Body gyroscope magnitude of three-dimensional frequency domain Jerk Signal, index of the frequency component with largest magnitude
        number
                -1..1
###fBodyBodyGyroJerkMag-meanFreq
Body gyroscope magnitude of three-dimensional frequency domain Jerk Signal,  Weighted average of the frequency components to obtain a mean frequency
        number
                -1..1
###fBodyBodyGyroJerkMag-skewness
Body gyroscope magnitude of three-dimensional frequency domain Jerk Signal, skewness of the frequency domain Jerk signal
        number
                -1..1
###fBodyBodyGyroJerkMag-kurtosis
Body gyroscope magnitude of three-dimensional frequency domain Jerk Signal, kurtosis of the frequency domain Jerk signal
        number
                -1..1
###angle(tBodyAccMean,gravity)
Angle between to vectors tBodyAccMean and gravity.
        number
                -1..1
###angle(tBodyAccJerkMean),gravityMean)
Angle between to vectors.
        number
                -1..1
###angle(tBodyGyroMean,gravityMean)
Angle between to vectors.
        number
                -1..1
###angle(tBodyGyroJerkMean,gravityMean)
Angle between to vectors.
        number
                -1..1
###angle(X,gravityMean)
Angle between to vectors.
        number
                -1..1
###angle(Y,gravityMean)
Angle between to vectors.
        number
                -1..1
###angle(Z,gravityMean)
Angle between to vectors.
        number
                -1..1